import { Component } from '@angular/core';
import { AccountService } from '../../services/account.service';
import { NgForm } from '@angular/forms';
import { JwtService } from '../../services/jwt.service';
import { Router } from '@angular/router';
import { Account } from '../../models/account.model'; // Import the Account model

@Component({
  selector: 'app-add-account',
  templateUrl: './add-account.component.html',
  styleUrls: ['./add-account.component.css']
})
export class AddAccountComponent {
  userRole: string;

  account: Account = {
    AccountId: 0, // This will be auto-generated by the server
    UserId: 0,    // Will be set from localStorage
    Balance: 0,
    AccountType: ''
  };

  constructor(private accountService: AccountService, private jwtService: JwtService, private router: Router) {
    this.userRole = this.jwtService.getUserRole();
  }

  addAccount(form: NgForm): void {
    if (form.valid) {
      // Retrieve UserId from localStorage
      const userId = Number(localStorage.getItem('userId'));
      
      if (userId) {
        // Set UserId to the account object
        this.account.UserId = userId;
        
        // Call the service to add the account
        this.accountService.addAccount(this.account).subscribe(
          () => {
            alert('Account added successfully!');
            this.router.navigate(['/view/account']);
          },
          (error) => {
            console.error('Error adding account:', error);
          }
        );
      } else {
        console.error('User ID not found in localStorage.');
      }
    }
  }
}
